use <../lib.scad>
use <../p/box4-1.scad>
use <../p/box5.scad>
use <../p/clh10.scad>
use <../p/rect.scad>
use <../p/rect3.scad>
use <s/57906s01.scad>
use <../p/stud.scad>
use <../p/stud3.scad>
$fa=1; $fs=0.2;
function ldraw_lib__57906(realsolid=false) = [
// 0 Hinge Plate  1 x 12 with Angled Sides and Tapered Ends
// 0 Name: 57906.dat
// 0 Author: Greg Teft [gregteft]
// 0 !LDRAW_ORG Part UPDATE 2012-01
// 0 !LICENSE Licensed under CC BY 2.0 and CC BY 4.0 : see CAreadme.txt
// 
// 0 BFC CERTIFY CCW
  [0,"BFC","CERTIFY"],
  [0,"BFC","CCW"],
// 
// 0 !HISTORY 2007-08-25 {LEGO Universe Team} Original part shape
// 0 !HISTORY 2009-03-02 [gregteft] File preparation for LDraw Parts Tracker
// 0 !HISTORY 2012-03-30 [PTadmin] Official Update 2012-01
// 
// 
// 0 // symmetrical placements
// 
// 1 16 0 0 0 1 0 0 0 1 0 0 0 1 s\57906s01.dat
  [1,16,0,0,0,1,0,0,0,1,0,0,0,1, ldraw_lib__s__57906s01(realsolid)],
// 1 16 0 0 0 1 0 0 0 1 0 0 0 -1 s\57906s01.dat
  [1,16,0,0,0,1,0,0,0,1,0,0,0,-1, ldraw_lib__s__57906s01(realsolid)],
// 1 16 126 2 0 0 0 1 0 1 0 -1 0 0 clh10.dat
  [1,16,126,2,0,0,0,1,0,1,0,-1,0,0, ldraw_lib__clh10(realsolid)],
// 1 16 126 2 0 0 0 1 0 1 0 1 0 0 clh10.dat
  [1,16,126,2,0,0,0,1,0,1,0,1,0,0, ldraw_lib__clh10(realsolid)],
// 0 // plate geometry
// 0 BFC INVERTNEXT
  [0,"BFC","INVERTNEXT"],
// 1 16 60 8 0 57 0 0 0 -5 0 0 0 7 box5.dat
  [1,16,60,8,0,57,0,0,0,-5,0,0,0,7, ldraw_lib__box5(realsolid)],
// 1 16 10 0 0 1 0 0 0 1 0 0 0 1 stud.dat
  [1,16,10,0,0,1,0,0,0,1,0,0,0,1, ldraw_lib__stud(realsolid)],
// 1 16 30 0 0 1 0 0 0 1 0 0 0 1 stud.dat
  [1,16,30,0,0,1,0,0,0,1,0,0,0,1, ldraw_lib__stud(realsolid)],
// 1 16 50 0 0 1 0 0 0 1 0 0 0 1 stud.dat
  [1,16,50,0,0,1,0,0,0,1,0,0,0,1, ldraw_lib__stud(realsolid)],
// 1 16 70 0 0 1 0 0 0 1 0 0 0 1 stud.dat
  [1,16,70,0,0,1,0,0,0,1,0,0,0,1, ldraw_lib__stud(realsolid)],
// 1 16 90 0 0 1 0 0 0 1 0 0 0 1 stud.dat
  [1,16,90,0,0,1,0,0,0,1,0,0,0,1, ldraw_lib__stud(realsolid)],
// 1 16 110 0 0 1 0 0 0 1 0 0 0 1 stud.dat
  [1,16,110,0,0,1,0,0,0,1,0,0,0,1, ldraw_lib__stud(realsolid)],
// 1 16 20 3 0 1 0 0 0 -1.25 0 0 0 1 stud3.dat
  [1,16,20,3,0,1,0,0,0,-1.25,0,0,0,1, ldraw_lib__stud3(realsolid)],
// 1 16 40 3 0 1 0 0 0 -1.25 0 0 0 1 stud3.dat
  [1,16,40,3,0,1,0,0,0,-1.25,0,0,0,1, ldraw_lib__stud3(realsolid)],
// 1 16 60 3 0 1 0 0 0 -1.25 0 0 0 1 stud3.dat
  [1,16,60,3,0,1,0,0,0,-1.25,0,0,0,1, ldraw_lib__stud3(realsolid)],
// 1 16 80 3 0 1 0 0 0 -1.25 0 0 0 1 stud3.dat
  [1,16,80,3,0,1,0,0,0,-1.25,0,0,0,1, ldraw_lib__stud3(realsolid)],
// 1 16 100 3 0 1 0 0 0 -1.25 0 0 0 1 stud3.dat
  [1,16,100,3,0,1,0,0,0,-1.25,0,0,0,1, ldraw_lib__stud3(realsolid)],
// 1 16 3 5.25 0 0 1 0 0 0 2.25 1 0 0 box4-1.dat
  [1,16,3,5.25,0,0,1,0,0,0,2.25,1,0,0, ldraw_lib__box4_1(realsolid)],
// 1 16 117 5.25 0 0 -1 0 0 0 2.25 -1 0 0 box4-1.dat
  [1,16,117,5.25,0,0,-1,0,0,0,2.25,-1,0,0, ldraw_lib__box4_1(realsolid)],
// 0 // geometry generated by teft.greg.dxftodat.DxfToDat
// 1 16 -60 3 0 60 0 0 0 -1 0 0 0 -9.2 rect.dat
  [1,16,-60,3,0,60,0,0,0,-1,0,0,0,-9.2, ldraw_lib__rect(realsolid)],
// 1 16 0 0 0 120 0 0 0 1 0 0 0 10 rect.dat
  [1,16,0,0,0,120,0,0,0,1,0,0,0,10, ldraw_lib__rect(realsolid)],
// 1 16 120 4 0 0 -1 0 0 0 4 -4 0 0 rect3.dat
  [1,16,120,4,0,0,-1,0,0,0,4,-4,0,0, ldraw_lib__rect3(realsolid)],
// 2 24 0 8 10 0 8 -10
  [2,24,0,8,10,0,8,-10],
// 4 16 -120 3 9.2 -120 3 -9.2 -120 0 -10 -120 0 10
  [4,16,-120,3,9.2,-120,3,-9.2,-120,0,-10,-120,0,10],
// 4 16 117 8 -7 117 8 7 120 8 10 120 8 -10
  [4,16,117,8,-7,117,8,7,120,8,10,120,8,-10],
// 4 16 0 8 10 0 8 -10 0 3 -9.2 0 3 9.2
  [4,16,0,8,10,0,8,-10,0,3,-9.2,0,3,9.2],
// 4 16 3 8 7 3 8 -7 0 8 -10 0 8 10
  [4,16,3,8,7,3,8,-7,0,8,-10,0,8,10],
// 0
];
module ldraw_lib__57906(step=0, col=false, unit=2/5, alt=false, line=0.2, solid=!$preview)
    makepoly(ldraw_lib__57906(solid), step=step, col=col, unit=unit, alt=alt, line=line, solid=solid);
ldraw_lib__57906(line=0.2);